"""Remove UNIQUE constraint from ISBN column

Revision ID: 35858064282d
Revises: 985a9cfdddd3
Create Date: 2023-09-15 09:11:29.504148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35858064282d'
down_revision = '985a9cfdddd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
