"""Add new_column to Book table

Revision ID: 597cc47b0d25
Revises: b46c4a5a16a6
Create Date: 2023-09-17 11:47:26.690591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597cc47b0d25'
down_revision = 'b46c4a5a16a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp_books')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('Quantity')

    op.create_table('temp_books',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('author', sa.TEXT(), nullable=True),
    sa.Column('isbn', sa.TEXT(), nullable=True),
    sa.Column('publisher', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
