"""Add QUANTITY to books table

Revision ID: b0e690cdedfe
Revises: 597cc47b0d25
Create Date: 2023-09-17 12:01:49.718567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0e690cdedfe'
down_revision = '597cc47b0d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('Quantity')

    # ### end Alembic commands ###
